# Generated by Django 5.2.5 on 2025-09-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_remove_message_chat_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('support', 'Support Agent')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 157557', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
