# Generated by Django 5.2.5 on 2025-09-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_account_chat_message_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='customer',
        ),
        migrations.AddField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 675419', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
