# Generated by Django 5.2.5 on 2025-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_message_created_at_remove_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 997157', editable=False, max_length=20, unique=True),
        ),
    ]
