# Generated by Django 5.2.5 on 2025-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_trade_customer_trade_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='action',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(blank=True, choices=[('BTC/USD', 'BTC/USD'), ('ETH/USD', 'ETH/USD'), ('XRP/USD', 'XRP/USD'), ('LTC/USD', 'LTC/USD'), ('ADA/USD', 'ADA/USD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 839445', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='leverage',
            field=models.CharField(choices=[('1x', '1x'), ('5x', '5x'), ('10x', '10x'), ('25x', '25x'), ('50x', '50x')], default='1x', max_length=3),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
