# Generated by Django 5.2.5 on 2025-09-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 470888', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='trade.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('BTC/USD', 'BTC/USD'), ('ETH/USD', 'ETH/USD')], max_length=100),
        ),
    ]
