# Generated by Django 5.2.5 on 2025-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_trade_options_trade_status_trade_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='customer_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 540508', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=100, null=True),
        ),
    ]
