# Generated by Django 5.2.5 on 2025-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_account_account_number_alter_account_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 710667', editable=False, max_length=20, unique=True),
        ),
    ]
