# Generated by Django 5.2.5 on 2025-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_transaction_is_canceled_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='customer_profit',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 588988', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('credited', 'credited'), ('approved', 'approved'), ('failed', 'failed')], default='pending', max_length=100),
        ),
    ]
