# Generated by Django 5.2.5 on 2025-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_trade_customer_profit_trade_profit_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 122813', editable=False, max_length=20, unique=True),
        ),
    ]
