# Generated by Django 5.2.5 on 2025-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_remove_trade_customer_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 164975', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='BUY', max_length=4),
        ),
    ]
