# Generated by Django 5.2.5 on 2025-09-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_alter_account_account_number_alter_trade_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 233221', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
    ]
