# Generated by Django 5.2.5 on 2025-09-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_alter_account_account_number_alter_trade_trade_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='close_trade',
            new_name='allow_close_trade',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 707456', editable=False, max_length=20, unique=True),
        ),
    ]
