# Generated by Django 5.2.5 on 2025-09-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_rename_close_trade_trade_allow_close_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 406888', editable=False, max_length=20, unique=True),
        ),
    ]
