# Generated by Django 5.2.5 on 2025-09-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 787924', editable=False, max_length=20, unique=True),
        ),
    ]
