# Generated by Django 5.2.5 on 2025-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='PW2025 3304', editable=False, max_length=20, unique=True),
        ),
    ]
