# Generated by Django 5.2.5 on 2025-09-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_referalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referalcode',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
