# Generated by Django 5.2.5 on 2025-09-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_referalcode_is_expired'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferalCode',
            new_name='ReferralCode',
        ),
    ]
