# Generated by Django 5.2.5 on 2025-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_referalcode_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pws',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
